export const LIST_EDIT_DATE = 'LIST_EDIT_DATE'
export const SELECT_EDIT_DATE = 'SELECT_EDIT_DATE'
export const ADD_LIST_DATE = 'ADD_LIST_DATE'
export const LIST_ID_DATE ='LIST_ID_DATE'
export const ID_SELECT = 'ID_SELECT'
export const PUT_EDIT_DATE = 'PUT_EDIT_DATE' 
